language: python
sudo: false
notifications:
    email: change

python:
    - 3.6

matrix:
  include:
    - python: 3.6
      env:
        - STYLE=1
    - python: 3.6
      env:
        - COVERAGE=1

before_install:
    - python -m pip install --upgrade pip
    - if [ "${STYLE}" == "1" ]; then
          pip install flake8;
      fi
    - if [ "${COVERAGE}" == "1" ]; then
          pip install coverage coveralls codecov pytest pytest-cov;
      fi

install:
    - python setup.py install

script:
    - |
      if [ "${STYLE}" == "1" ]; then
          flake8 abagen
      else
          if [ "${COVERAGE}" == "1" ]; then
              TEST_ARGS="--cov-report term-missing --cov=abagen";
          fi
          py.test ${TEST_ARGS} abagen;
      fi

after_success:
    - if [ "${COVERAGE}" == "1" ]; then
          coveralls; codecov;
      fi
