language: python
sudo: false
dist: xenial
notifications:
  email: change

branches:
  only:
    - master

python:
  - 3.5
  - 3.6
  - 3.7

env:
  matrix:
    - CHECK_TYPE=docdoctest

before_install:
  - python -m pip install --upgrade pip

install:
  - python setup.py install;

script:
  - |
    cd docs;
    pip install -r ./requirements.txt;
    make html;
    travis_wait 40 make doctest;
