language: python
cache: pip
sudo: false
notifications:
  email: change

python:
  - 3.5
  - 3.6

env:
  - LINTING=1
  - DOCTEST=1

matrix:
  include:
  - python: 3.5
    sudo: required
    env:
      - PARQUET=1
  - python: 3.6
    sudo: required
    env:
      - PARQUET=1
      - COVERAGE=1
  - python: 3.7
    dist: xenial
    sudo: required
  - python: 3.7
    dist: xenial
    sudo: required
    env:
      - DOCTEST=1

before_install:
  - python -m pip install --upgrade pip
  - if [ "${LINTING}" == "1" ]; then
      pip install flake8;
    fi
  - if [ "${COVERAGE}" == "1" ]; then
      pip install coverage coveralls codecov;
    fi
  - if [ "${PARQUET}" == "1" ]; then
      sudo apt-get install libsnappy-dev;
    fi

install:
  - if [ "${PARQUET}" == "1" ]; then
      pip install -e .[io,tests];
    elif [ "${DOCTEST}" == "1" ]; then
      pip install -e .[doc];
    else
      pip install -e .[tests];
    fi

script:
  - |
    if [ "${LINTING}" == "1" ]; then
      flake8 abagen;
    elif [ "${DOCTEST}" == "1" ]; then
      cd docs;
      make html;
      make doctest;
    else
      if [ "${COVERAGE}" == "1" ]; then
        TEST_ARGS="--cov-report term-missing --cov=abagen";
      fi
      travis_wait py.test ${TEST_ARGS} abagen;
    fi

after_success:
  - if [ "${COVERAGE}" == "1" ]; then
      coveralls; codecov;
    fi
