
parameters:
  name: ''
  vmImage: ''
  matrix: []

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      ${{ insert }}: ${{ parameters.matrix }}

  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(PYTHON_VERSION)'
        addToPath: true
        architecture: '$(PYTHON_ARCH)'
    - script: |
        python -m pip install --upgrade pip setuptools>=30.3.0 wheel
      displayName: 'Update build tools'
    - script: |
        python -m pip install --find-links nibabel numpy pandas scipy
        python -m pip install pytest pytest-cov codecov
      displayName: 'Install dependencies'
    - script: |
        python -m pip install .
        SET ABAGEN_DATA=%CD%\\abagen-data
      displayName: 'Install abagen'
    - script: |
        mkdir for_testing
        cd for_testing
        cp ../setup.cfg .
        pytest --cov-report term-missing --cov=abagen --doctest-modules --pyargs abagen
      displayName: 'Run tests'
    - script: |
        cd for_testing
        codecov
      displayName: 'Upload To Codecov'
      env:
        CODECOV_TOKEN: $(CODECOV_TOKEN)
